### PR TITLE
webwork database description

### PR DESCRIPTION
**Pull request by airanmehr**

### CODE REVIEW

**Comment by yoavfreund** [comment]
Zhen, please give Arya an account on webwork so that he can probe the database to find out all of the schema.

Also, I ask him to help you in creating a database storage for the filters.

Yoav

**Comment by airanmehr** [comment]
Zhen
let me know whenever you are available,

**Comment by yoavfreund** [comment]
Hi Guys and Girls,

I am having a hard time getting google hangout to work for everybody.

Instead, I suggest that you join hipchat and we emeet there.

You should have gotten an email, but if not, the url is


https://ucsddse200.hipchat.com/chat/room/2008318

Yoav

**Comment by yoavfreund** [comment]
Hi Guys,

Tomorrow I am going to cover Minhash and it's use for document comparison
and Bloom filters.

I am not happy with the problems we currently have on webwork for these
subjects. They are extremely long and require more memorization than
thinking.

I would like to replace them with a series of problems, each focusing on a
different aspect. My current status is below.

I would like to ask you to write the problems in the webwork PGML format.

Please get on hipchat so we can coordinate.

I moved the start of HW9 to tomorrow at 5pm.

Yoav

**Pull request closed without merging**
